import 'package:drive_easy/classes/game/item.dart';
import 'package:drive_easy/global.dart';

Map<String, List<Item>> requestsOnBoard = {
  "level0": [
    Item(
      reqId: 0,
      name: "request 0",
      reqType: RequestType.upload,
      fileType: FileType.file,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 1,
      name: "request 1",
      reqType: RequestType.upload,
      fileType: FileType.file,
      source: Drives.local,
      destination: "Googgle Drive",
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 2,
      name: "request 2",
      reqType: RequestType.upload,
      fileType: FileType.file,
      source: Drives.local,
      destination: Drives.icloud,
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 3,
      name: "request 3",
      reqType: RequestType.upload,
      fileType: FileType.file,
      source: Drives.local,
      destination: "jcloud",
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 999,
      name: "Hi",
      reqType: "Hoi",
      fileType: "HeLLo",
      source: "0.0.0.0",
      destination: "HAllo",
      encryption: "plain",
      action: "olleh",
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 8,
      score: 0,
    ),
  ],
  "level1": [
    Item(
      reqId: 0,
      name: "Upload File",
      reqType: RequestType.upload,
      fileType: FileType.file,
      source: Drives.local,
      destination: Drives.mega,
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 1,
      name: "Download file",
      reqType: RequestType.download,
      fileType: FileType.folder,
      source: Drives.dropbox,
      destination: Drives.local,
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 2,
      name: "request 2",
      reqType: "delete",
      fileType: FileType.folder,
      source: Drives.googleDrive,
      destination: Drives.dropbox,
      encryption: "3-DES",
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
    ),
    Item(
      reqId: 3,
      name: "uPlOaD fIlE",
      reqType: RequestType.upload,
      fileType: FileType.Third_party_shortcut,
      source: Drives.local,
      destination: Drives.icloud,
      encryption: Encryption.AES128,
      action: ActionType.GET,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
    ),
    Item(
      reqId: 4,
      name: "request 4",
      reqType: RequestType.download,
      fileType: FileType.file,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES128,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 5,
      name: "sudo dl someone's file",
      reqType: RequestType.download,
      fileType: FileType.folder,
      source: Drives.oneDrive,
      destination: "C:/user/Peter",
      encryption: "plain-text",
      action: ActionType.GET,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
    ),
    Item(
      reqId: 6,
      name: "request 6",
      reqType: RequestType.download,
      fileType: "image",
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES256,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
    ),
    Item(
      reqId: 7,
      name: "7",
      reqType: RequestType.download,
      fileType: "video",
      source: "my phone",
      destination: "my PC",
      encryption: "plain-text",
      action: ActionType.GET,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 4,
      score: 0,
    ),
  ],
  "level2": [
    Item(
      reqId: 0,
      name: "request 0",
      reqType: RequestType.upload,
      fileType: FileType.folder,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES128,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
      authSituation: 0,
    ),
  ],
  "level3": [
    Item(
      reqId: 0,
      name: "request 0",
      reqType: RequestType.upload,
      fileType: FileType.folder,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES128,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
      authSituation: 1,
    ),
    Item(
      reqId: 0,
      name: "request 0",
      reqType: RequestType.upload,
      fileType: FileType.folder,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES128,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 3,
      score: 0,
      authSituation: 2,
    ),
  ],
  "level4": [
    Item(
      reqId: 0,
      name: "request 0",
      reqType: RequestType.upload,
      fileType: FileType.folder,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES128,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 2, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 6,
      score: 0,
      authSituation: 0,
      key: Item.randomStringGenerator(length: 32, pool: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"),
      content: Item.randomStringGenerator(length: 50) + " **function(){execute:delete\tall\tfiles;} " + Item.randomStringGenerator(length: 850)
    ),
  ]
};