import 'package:drive_easy/classes/game/item.dart';
import 'package:drive_easy/global.dart';

Map<String, List<Item>> requestsOnBoard = {
  "level0": [
    Item(
      reqId: 0,
      name: "request 0",
      reqType: RequestType.uplaod,
      fileType: FileType.file,
      source: Drives.local,
      destination: Drives.googleDrive,
      encryption: Encryption.AES256,
      content: dummyContent,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 1,
      name: "request 1",
      reqType: RequestType.uplaod,
      fileType: FileType.file,
      source: Drives.local,
      destination: "Googgle Drive",
      encryption: Encryption.AES256,
      content: dummyContent,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 2,
      name: "request 2",
      reqType: RequestType.uplaod,
      fileType: FileType.file,
      source: Drives.local,
      destination: Drives.icloud,
      encryption: Encryption.AES256,
      content: dummyContent,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 3,
      name: "request 3",
      reqType: RequestType.uplaod,
      fileType: FileType.file,
      source: Drives.local,
      destination: "jcloud",
      encryption: Encryption.AES256,
      content: dummyContent,
      action: ActionType.POST,
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 2,
      score: 0,
    ),
    Item(
      reqId: 999,
      name: "Hi",
      reqType: "Hoi",
      fileType: "HeLLo",
      source: "0.0.0.0",
      destination: "HAllo",
      encryption: "plain",
      content: ["hihihihihi"],
      action: "olleh",
      sessionTime: DateTime(2022, 4, 1, 09, 00),
      timeNeeded: Duration(hours: 1),
      totalScore: 8,
      score: 0,
    ),
  ],
};